#!/usr/bin/env node
/**
 * 用 esbuild 把 client 半区打成 DSH 浏览器模块加载器 handoff：
 *
 *   window.__ModuleLoader__.load({
 *     id: '<包名>',
 *     factory: (require) => { ... }
 *   })
 *
 * esbuild 负责内联所有源码模块（src/projection.ts 等），只把平台模块
 * （react / @deepseek-ai/cordis）留在 require() 上，由浏览器加载器模块表解析
 * （与 DSH 官方 tsdown clientBundle 的 external 列表一致）。
 * 输出覆盖写回 lib/client.js（package.json exports["./client"] 指向的文件）。
 */
import { build } from 'esbuild'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const clientFile = join(root, 'lib', 'client.js')
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))

const result = await build({
  entryPoints: [join(root, 'src', 'client.ts')],
  bundle: true,
  format: 'cjs',
  platform: 'browser',
  write: false,
  // 平台模块（模块表）保持 external；其余依赖全部内联。
  external: ['react', '@deepseek-ai/cordis'],
  define: {
    'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV ?? 'production'),
  },
  logLevel: 'silent',
})
const bundleBody = result.outputFiles[0].text

// 工厂闭包内提供 module/exports 垫片（esbuild CJS 输出需要），并把加载器的
// require 传给入口默认导出的 factory(require)。
const handoff = [
  '/* GENERATED by scripts/build-client.mjs — do not edit. */',
  'window.__ModuleLoader__.load({',
  `  id: ${JSON.stringify(pkg.name)},`,
  '  factory: (require) => {',
  '    const module = { exports: {} };',
  '    const exports = module.exports;',
  bundleBody.trimEnd(),
  '    return module.exports.default(require);',
  '  },',
  '})',
  '',
].join('\n')

writeFileSync(clientFile, handoff)
console.log(`client bundle written: lib/client.js (id=${pkg.name})`)
