#!/usr/bin/env node
/**
 * 把 tsc 编译出的 lib/client.js（`export default function factory(require) {...}`）
 * 包装成 DSH 浏览器模块加载器 handoff，覆盖写回 lib/client.js：
 *
 *   window.__ModuleLoader__.load({
 *     id: '<包名>',
 *     factory: function factory(require) { ... },
 *   })
 *
 * 这是 DSH web 端 /plugins/<id>/client.js 的实际执行格式（见
 * packages/client/modules 的 ClientPluginHandoff）。打包脚本剥离 `export default `
 * 前缀后内联 factory 源码，因此 client 半区可以继续用 TypeScript 编写和类型检查。
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const clientFile = join(root, 'lib', 'client.js')
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))

const compiled = readFileSync(clientFile, 'utf8')
const marker = 'export default '
const markerIndex = compiled.indexOf(marker)
if (markerIndex === -1) {
  throw new Error(`lib/client.js 不是预期的 tsc 产物（缺少 "${marker}" 前缀）；先运行 tsc`)
}
// 模块作用域（常量 / 辅助函数 / JSDoc）保留在 handoff 顶层，factory 引用它们；
// 从 `export default ` 标记处起切出 factory 函数本身。
const moduleScope = compiled.slice(0, markerIndex).trimEnd()
const factorySource = compiled.slice(markerIndex + marker.length).trimEnd()

const handoff = [
  '/* GENERATED by scripts/build-client.mjs — do not edit. */',
  moduleScope,
  'window.__ModuleLoader__.load({',
  `  id: ${JSON.stringify(pkg.name)},`,
  `  factory: ${factorySource},`,
  '})',
  '',
].join('\n')

writeFileSync(clientFile, handoff)
console.log(`client bundle written: lib/client.js (id=${pkg.name})`)
